v1.5
Craftserve/CraftserveRadiation pull request #50
Opened 2022-06-22 15:11 UTC by Skyy0x

2022-06-29 13:15 UTC, TheMolkaPL requested changes
Czy te zmiany były testowane?

2022-06-29 13:15 UTC, TheMolkaPL commented on src/main/java/pl/craftserve/radiation/nms/V1_19_R1NmsBridge.java
> +            this.isRegistryMaterialsFrozen = registryMaterialsClass.getDeclaredField("ca"); // bL -> frozen
```suggestion
            this.isRegistryMaterialsFrozen = registryMaterialsClass.getDeclaredField("ca"); // ca -> frozen

```

2022-06-29 13:15 UTC, TheMolkaPL commented on src/main/java/pl/craftserve/radiation/nms/V1_19_R1NmsBridge.java
> +            this.potionRegistry = this.iRegistryClass.getDeclaredField("Z").get(null); // Y -> POTION_REGISTRY
```suggestion
            this.potionRegistry = this.iRegistryClass.getDeclaredField("Z").get(null); // Z -> POTION_REGISTRY

```

2022-06-30 12:07 UTC, Skyy0x commented
> 

Tak były

2022-06-30 14:22 UTC, TheMolkaPL commented
Dobrze. Proszę w takim razie o wykonanie zmian które zaproponowałem i mogę mergować.

2022-06-30 14:28 UTC, TheMolkaPL commented
Proszę jeszcze dopisać do README, że plugin wspiera 1.19.

https://github.com/Craftserve/CraftserveRadiation/blob/abe0018ee7be3e75a65bb3d3aca8c9dc26414a90/README.md?plain=1#L5

2022-07-12 11:10 UTC, TheMolkaPL approved these changes

2022-07-12 11:10 UTC, merged

2022-07-12 11:11 UTC, TheMolkaPL commented
Dziękuję za kontrybucję!